# Generated by Django 3.1.7 on 2021-07-31 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_at', models.DateTimeField(default=datetime.datetime(2021, 7, 31, 9, 48, 3, 364264))),
                ('name', models.CharField(max_length=1000)),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
    ]
