# Generated by Django 3.1.7 on 2021-07-31 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210731_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='files',
            name='upload_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 14, 15, 13, 8076)),
        ),
    ]
