# Generated by Django 3.1.7 on 2021-07-31 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210731_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='upload_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 14, 32, 23, 247250)),
        ),
    ]
