# Generated by Django 3.1.7 on 2021-07-31 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210731_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='upload_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 16, 41, 36, 351075)),
        ),
    ]
