# Generated by Django 3.1.7 on 2021-08-01 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210801_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='upload_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 14, 28, 14, 50405)),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
