# Generated by Django 3.1.7 on 2021-08-01 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20210801_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='upload_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 14, 30, 4, 146977)),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='1', max_length=1, primary_key=True, serialize=False),
        ),
    ]
