# Generated by Django 3.1.7 on 2021-08-01 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20210801_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='likeuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_on', models.DateTimeField(default=datetime.datetime(2021, 8, 1, 19, 35, 30, 67702))),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='files',
            name='upload_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 19, 35, 29, 978935)),
        ),
    ]
