# Generated by Django 3.1.7 on 2021-08-02 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20210801_1935'),
    ]

    operations = [
        migrations.DeleteModel(
            name='likeuser',
        ),
        migrations.RemoveField(
            model_name='like',
            name='ids',
        ),
        migrations.AddField(
            model_name='like',
            name='like_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 19, 38, 57, 869771)),
        ),
        migrations.AddField(
            model_name='like',
            name='name',
            field=models.CharField(default='Unknown', max_length=1000),
        ),
        migrations.AlterField(
            model_name='files',
            name='upload_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 19, 38, 57, 773732)),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='likeno',
            field=models.CharField(default='1', max_length=10000),
        ),
    ]
