# Generated by Django 3.1.7 on 2021-08-02 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20210802_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='lock',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='files',
            name='password',
            field=models.CharField(default='non', max_length=100),
        ),
        migrations.AlterField(
            model_name='files',
            name='upload_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 19, 45, 58, 557311)),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 19, 45, 58, 645102)),
        ),
    ]
