# Generated by Django 3.1.7 on 2021-08-03 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20210802_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='password',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='files',
            name='upload_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 13, 21, 32, 734993)),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 13, 21, 32, 772884)),
        ),
    ]
