# Generated by Django 3.1.7 on 2021-08-04 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20210803_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file_id',
            field=models.CharField(default='23s76hr2516zone562sh83', max_length=1000),
        ),
        migrations.AlterField(
            model_name='files',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='files',
            name='upload_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 18, 13, 41, 267098)),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 18, 13, 41, 324266)),
        ),
    ]
