# Generated by Django 3.1.7 on 2021-08-04 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20210804_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_id',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='files',
            name='upload_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 18, 51, 29, 612790)),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 18, 51, 29, 647687)),
        ),
    ]
